// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutFunctionRequest {
    /// The cache within which the Function is stored.
    #[prost(string, tag = "1")]
    pub cache_name: ::prost::alloc::string::String,
    /// Friendly name for the Function. This is used to call the Function, so call it what you want to use to call it.
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// Optional description for the Function. You can use this to keep some notes about this Function.
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    /// The environment variables that are available to this function as virtual environment via the WASI interface.
    #[prost(map = "string, message", tag = "4")]
    pub environment: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        super::function_types::EnvironmentValue,
    >,
    #[prost(oneof = "put_function_request::WasmLocation", tags = "20, 21")]
    pub wasm_location: ::core::option::Option<put_function_request::WasmLocation>,
}
/// Nested message and enum types in `_PutFunctionRequest`.
pub mod put_function_request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum WasmLocation {
        /// The wasm for the Function is here, in the message. Will be uploaded as a separate Wasm
        #[prost(bytes, tag = "20")]
        Inline(::prost::alloc::vec::Vec<u8>),
        /// The wasm for the Function is this id
        #[prost(message, tag = "21")]
        WasmId(super::super::function_types::WasmId),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutFunctionResponse {
    #[prost(message, optional, tag = "1")]
    pub function: ::core::option::Option<super::function_types::Function>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutWasmRequest {
    /// Name for the Wasm
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// Optional description for the Wasm. You can use this to keep some notes about this Wasm
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(oneof = "put_wasm_request::WasmPutKind", tags = "22, 24")]
    pub wasm_put_kind: ::core::option::Option<put_wasm_request::WasmPutKind>,
}
/// Nested message and enum types in `_PutWasmRequest`.
pub mod put_wasm_request {
    #[derive(Clone, Copy, PartialEq, ::prost::Message)]
    pub struct MetadataOnly {}
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum WasmPutKind {
        /// The bytes for the wasm are here in the message
        #[prost(bytes, tag = "22")]
        Inline(::prost::alloc::vec::Vec<u8>),
        /// No bytes change necessary, just changing the metadata of the record (description, display name, etc.)
        #[prost(message, tag = "24")]
        MetadataOnly(MetadataOnly),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PutWasmResponse {
    #[prost(message, optional, tag = "1")]
    pub wasm: ::core::option::Option<super::function_types::Wasm>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListWasmsRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFunctionsRequest {
    /// The cache to list functions in.
    #[prost(string, tag = "1")]
    pub cache_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListFunctionVersionsRequest {
    /// List the versions of a given function
    #[prost(string, tag = "1")]
    pub function_id: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod function_registry_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// A Function is an extension of Momento; for users to build their own Momento apis.
    /// This is the registration and management interface.
    #[derive(Debug, Clone)]
    pub struct FunctionRegistryClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl FunctionRegistryClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> FunctionRegistryClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> FunctionRegistryClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            FunctionRegistryClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Register a new Function. This will overwrite any existing Function with the same name.
        /// Functions are registered within a cache, which namespaces them.
        pub async fn put_function(
            &mut self,
            request: impl tonic::IntoRequest<super::PutFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutFunctionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/function.FunctionRegistry/PutFunction",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("function.FunctionRegistry", "PutFunction"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn put_wasm(
            &mut self,
            request: impl tonic::IntoRequest<super::PutWasmRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutWasmResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/function.FunctionRegistry/PutWasm",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("function.FunctionRegistry", "PutWasm"));
            self.inner.unary(req, path, codec).await
        }
        pub async fn list_functions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListFunctionsRequest>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<super::super::function_types::Function>,
            >,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/function.FunctionRegistry/ListFunctions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("function.FunctionRegistry", "ListFunctions"));
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn list_function_versions(
            &mut self,
            request: impl tonic::IntoRequest<super::ListFunctionVersionsRequest>,
        ) -> std::result::Result<
            tonic::Response<
                tonic::codec::Streaming<super::super::function_types::FunctionVersion>,
            >,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/function.FunctionRegistry/ListFunctionVersions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("function.FunctionRegistry", "ListFunctionVersions"),
                );
            self.inner.server_streaming(req, path, codec).await
        }
        pub async fn list_wasms(
            &mut self,
            request: impl tonic::IntoRequest<super::ListWasmsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::super::function_types::Wasm>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/function.FunctionRegistry/ListWasms",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("function.FunctionRegistry", "ListWasms"));
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod function_registry_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with FunctionRegistryServer.
    #[async_trait]
    pub trait FunctionRegistry: std::marker::Send + std::marker::Sync + 'static {
        /// Register a new Function. This will overwrite any existing Function with the same name.
        /// Functions are registered within a cache, which namespaces them.
        async fn put_function(
            &self,
            request: tonic::Request<super::PutFunctionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::PutFunctionResponse>,
            tonic::Status,
        >;
        async fn put_wasm(
            &self,
            request: tonic::Request<super::PutWasmRequest>,
        ) -> std::result::Result<tonic::Response<super::PutWasmResponse>, tonic::Status>;
        /// Server streaming response type for the ListFunctions method.
        type ListFunctionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::super::function_types::Function,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        async fn list_functions(
            &self,
            request: tonic::Request<super::ListFunctionsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ListFunctionsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the ListFunctionVersions method.
        type ListFunctionVersionsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::super::function_types::FunctionVersion,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        async fn list_function_versions(
            &self,
            request: tonic::Request<super::ListFunctionVersionsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::ListFunctionVersionsStream>,
            tonic::Status,
        >;
        /// Server streaming response type for the ListWasms method.
        type ListWasmsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<
                    super::super::function_types::Wasm,
                    tonic::Status,
                >,
            >
            + std::marker::Send
            + 'static;
        async fn list_wasms(
            &self,
            request: tonic::Request<super::ListWasmsRequest>,
        ) -> std::result::Result<tonic::Response<Self::ListWasmsStream>, tonic::Status>;
    }
    /// A Function is an extension of Momento; for users to build their own Momento apis.
    /// This is the registration and management interface.
    #[derive(Debug)]
    pub struct FunctionRegistryServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> FunctionRegistryServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for FunctionRegistryServer<T>
    where
        T: FunctionRegistry,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/function.FunctionRegistry/PutFunction" => {
                    #[allow(non_camel_case_types)]
                    struct PutFunctionSvc<T: FunctionRegistry>(pub Arc<T>);
                    impl<
                        T: FunctionRegistry,
                    > tonic::server::UnaryService<super::PutFunctionRequest>
                    for PutFunctionSvc<T> {
                        type Response = super::PutFunctionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PutFunctionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistry>::put_function(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutFunctionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/function.FunctionRegistry/PutWasm" => {
                    #[allow(non_camel_case_types)]
                    struct PutWasmSvc<T: FunctionRegistry>(pub Arc<T>);
                    impl<
                        T: FunctionRegistry,
                    > tonic::server::UnaryService<super::PutWasmRequest>
                    for PutWasmSvc<T> {
                        type Response = super::PutWasmResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::PutWasmRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistry>::put_wasm(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = PutWasmSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/function.FunctionRegistry/ListFunctions" => {
                    #[allow(non_camel_case_types)]
                    struct ListFunctionsSvc<T: FunctionRegistry>(pub Arc<T>);
                    impl<
                        T: FunctionRegistry,
                    > tonic::server::ServerStreamingService<super::ListFunctionsRequest>
                    for ListFunctionsSvc<T> {
                        type Response = super::super::function_types::Function;
                        type ResponseStream = T::ListFunctionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListFunctionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistry>::list_functions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListFunctionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/function.FunctionRegistry/ListFunctionVersions" => {
                    #[allow(non_camel_case_types)]
                    struct ListFunctionVersionsSvc<T: FunctionRegistry>(pub Arc<T>);
                    impl<
                        T: FunctionRegistry,
                    > tonic::server::ServerStreamingService<
                        super::ListFunctionVersionsRequest,
                    > for ListFunctionVersionsSvc<T> {
                        type Response = super::super::function_types::FunctionVersion;
                        type ResponseStream = T::ListFunctionVersionsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListFunctionVersionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistry>::list_function_versions(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListFunctionVersionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/function.FunctionRegistry/ListWasms" => {
                    #[allow(non_camel_case_types)]
                    struct ListWasmsSvc<T: FunctionRegistry>(pub Arc<T>);
                    impl<
                        T: FunctionRegistry,
                    > tonic::server::ServerStreamingService<super::ListWasmsRequest>
                    for ListWasmsSvc<T> {
                        type Response = super::super::function_types::Wasm;
                        type ResponseStream = T::ListWasmsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListWasmsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as FunctionRegistry>::list_wasms(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListWasmsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for FunctionRegistryServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "function.FunctionRegistry";
    impl<T> tonic::server::NamedService for FunctionRegistryServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
